on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: dockeracrtest1.azurecr.io
        username: ${{ secrets.acr_dockeracrtest1_username }}
        password: ${{ secrets.acr_dockeracrtest1_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/AngularMongo" -f  "AngularMongo/Dockerfile" -t dockeracrtest1.azurecr.io/dockertestcluster1:${{ github.sha }}
        docker push dockeracrtest1.azurecr.io/dockertestcluster1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_dockertestcluster1_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep dockertestcluster1b2eb | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace dockertestcluster1b2eb`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: dockertestcluster1b2eb
        container-registry-url: dockeracrtest1.azurecr.io
        container-registry-username: ${{ secrets.acr_dockeracrtest1_username }}
        container-registry-password: ${{ secrets.acr_dockeracrtest1_password }}
        secret-name: dockertestcldockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: dockertestcluster1b2eb
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          dockeracrtest1.azurecr.io/dockertestcluster1:${{ github.sha }}
        imagepullsecrets: |
          dockertestcldockerauth